# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: ae5a592b262dfc2dc6aeb4296032ae50754d4db4366c765e89fb3e9e57b37795b5588d105c3b2e58c1db110372366ea349567a451a0e74da6147258ec32ff08c

test:
  secret_key_base: f2b185a39ddb8edd1f36eb4481210a648a9ce9c787ba6c5798db2f6b294ca50763e39801942068cc72802ad155a114bcbc2571a94616d7bc6ce0cb58925bc833

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
